### ISSUE TITLE
NameError: name 'pfam_name' is not defined

### ISSUE THREAD

**Issue by snayfach** [AnantharamanLab/VIBRANT#18]
I've been getting this error on a subset of my runs:
```
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.conda/envs/vibrant/bin/VIBRANT_annotation.py", line 1708, in <module>
    AMG_dict.update({str(annotations[n]):str(annotations[n+1]).replace("$~&", " ").replace('^@%','"') + '\t' + str(annotations[n+2]) + '\t' + str(ko_name) + '\t' + str(annotations[n+6]) + '\t' + str(pfam_name)})
NameError: name 'pfam_name' is not defined
```

I'm running VIBRANT v1.2.0, installed with conda. Often, I can rerun the same command without any errors, so it doesn't seem to be reproducible.

Here is the command I'm using:
```
DB=$HOME/.conda/envs/vibrant/share/vibrant-1.0.1/databases/
VIBRANT_run.py -i $FNA -t 1 -virome -d $DB -folder out/${SLURM_ARRAY_TASK_ID}
```

**Comment by KrisKieft** [comment]
Hi,

This issue was just an oversight on my part when I pushed the new update. I actually fixed it right after I pushed the update but it looks like anaconda never updated. I'll try to get anaconda running the correct version as seen on GitHub.

Kris

**Comment by luayou** [comment]
Hi!
 
I just got the same issue. What should I do?

Traceback (most recent call last):
  File "/home/lave0001/.conda/envs/vibrant/bin/VIBRANT_annotation.py", line 1708, in <module>   
    AMG_dict.update({str(annotations[n]):str(annotations[n+1]).replace("$~&", " ").replace('^@%','"') + '\t' + str(annotations[n+2]) + '\t' + str(ko_name) + '\t' + str(annotations[n+6]) + '\t' + str(pfam_name)})
NameError: name 'pfam_name' is not defined
Traceback (most recent call last):
  File "/home/lave0001/.conda/envs/vibrant/bin/VIBRANT_run.py", line 582, in <module>
    genbank.write('//\nLOCUS       ' + str(genbank_database[n]) + '                 ' + str(length_database[genbank_database[n]]) + ' bp    DNA     ' + str(form) + '   VRL ' + str(date.today()) + '\nDEFINITION  ' + str(genbank_database[n]) + '.\nFEATURES             Location/Qualifiers\n     source          /organism="' + str(genbank_database[n]) + '"\n')
KeyError: 'uvig_336306'

**Comment by KrisKieft** [comment]
Hi,

Please try updating to v1.2.1, or if you already are running v1.2.1 try to re-install. With conda I believe this can be done with `conda install --force-reinstall vibrant==1.2.1` or if you installed via GitHub just replace all the files. You do not need to replace the databases. Let me know if that works.

Kris

**Comment by luayou** [comment]
Hi,

I've already reinstall vibrant 1.2.1 despite I've already had that version. I also checked the dependencies of the other packages, but I still have a similar

 problem, it seems that the problem is with that contig bc I have run vibrant several times, and I haven't had this error. 

'ivig_1999'
Traceback (most recent call last):
  File "/home/lave0001/.conda/envs/vibrant/bin/VIBRANT_run.py", line 599, in <module>
    genbank.write('//\nLOCUS       ' + str(genbank_database[n]) + '                     
         ' + str(length_database[genbank_database[n]]) + ' bp   DNA      ' + str(form) + '   VRL ' + str(date.today()) + '\nDEFINITION  ' + str(genbank_database[n]) + '.\nFEATURES                      Location/Qualifiers\n   source           /organism="' + str(genbank_database[n]) + '"\n')
KeyError: 'ivig_1999'

**Comment by luayou** [comment]
I found out that the problem is with the ID of the sequences, I renamed this set of contigs I the program works. :)

**Comment by KrisKieft** [comment]
Ok perfect, glad to hear you were able to figure it out. 

Kris

**Comment by WoCer2019** [comment]
Hi!

 I just got the same error. How should I rename this set of contigs, and let the program work？



> I found out that the problem is with the ID of the sequences, I renamed this set of contigs, and the program worked. :)

**Comment by KrisKieft** [comment]
Hi,

First, are you using v1.2.1? If not, try updating first. Otherwise, I would avoid using quotation marks, pipe symbols, and tabs. If you do not have any of these and it still isn't working then I may need to see an example sequence name.

**Comment by WoCer2019** [comment]
Hello,

Thank you. I have used v1.2.1. At present, no errors.

Kris Kieft ***@***.***> 于2022年3月12日周六 23:47写道：
