### ISSUE TITLE
VIBRANT not working VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py

### ISSUE THREAD

**Issue by Jlee795** [AnantharamanLab/VIBRANT#90]
Hi, 

I have been trying to use VIBRANT on linux. I installed it through Gitclone as I had trouble trying to install the usual way. I had the message saying vibrant was good to go but when I tried to run it on my data it didn't work. I checked the log and saw this message 

"VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py" 

I did what it said and ran vibrant set  up script and can see the pressed files in the databases folder 
e.g. 
 KEGG_profiles_prokaryotes.HMM
 KEGG_profiles_prokaryotes.HMM.h3i
 Pfam-A_v32.HMM
Pfam-A_v32.HMM.h3f
Pfam-A_v32.HMM.h3i
 Pfam-A_v32.HMM.h3m
 Pfam-A_v32.HMM.h3p

VOGDB94_phage.HMM
 VOGDB94_phage.HMM.h3f
 VOGDB94_phage.HMM.h3i
 VOGDB94_phage.HMM.h3m
VOGDB94_phage.HMM.h3p

tried running the command on my own data again and still got the same error message, can anyone advise what to do to fix this please?

Kind Regards, 

Jen

**Comment by Jlee795** [comment]
Hi @KrisKieft is there any ideas with this issue. I saw a closed issue with a solution to this by @BikramDroid. I tried their solution but this hasn't worked for me and I am still not really sure how to sort this. 

Any help greatly appreciated,

Kind Regards,

Jlee795

**Comment by KrisKieft** [comment]
I'm not sure what may have gone wrong but it looks like the database did not fully finish setting up. Can you please try removing `KEGG_profiles_prokaryotes.HMM.h3i` and then run `hmmpress KEGG_profiles_prokaryotes.HMM` in the directory where these files are stored.

**Comment by Jlee795** [comment]
Hi @KrisKieft. This issue has been resolved and Vibrant now runs things. However getting another problem. I was running your mixed example test dataset and had a look at the log file on the github page, your log file says four phages found but when I run the mixed test example dataset my log file says no phages found. Pretty sure that I should get the same output in the log as you get. Do you have any suggestions as to the cause? Any help is greatly appreciated. Thank you, 

Kind Regards, 

Jlee795

**Comment by Jlee795** [comment]
This is the output from my log file:

Command:  ../VIBRANT_run.py -i mixed_example_1.fasta -t 2 -folder example_test_mixed_3
Date:     2024-04-01
Start:    21:45:12
End:      21:46:18
Runtime:  1.1 minutes
Program:  VIBRANT v1.2.1


10 scaffolds were read in.
7 scaffolds met minimum requirements: at least 1000bp and 4 ORFs.
0 putative phages were identified.


CAUTION: running a version of Numpy lower than v1.17.0 will likely cause issues. With pip you can update by running "pip install --upgrade numpy==1.17.0".
                                                               ##
                                                             ##  ##
                                                           ##      ##
######   ##  ##     ##     #######   ######    #####       ##      ##
##  ##   ##  ##   ##  ##   ##        ##       ##             ##  ##
######   ######   ######   ##  ###   ######    ###             ##
##       ##  ##   ##  ##   ##   ##   ##           ##           ##
##       ##  ##   ##  ##   #######   ######   #####            ##
                                                            #  ##  #
                                                           # # ## # #
                                                          #   #  #   #
                                                         #            #

**Comment by Jlee795** [comment]
the version of Numpy in my environment is the very version it is mentioning under the caution. So I am not sure as to whether that is the cause. I downloaded VIBRANT as a git clone so it is version 1.2.1

**Comment by Jlee795** [comment]
@KrisKieft getting this error from the annotation log, which I think the problem of why no phages are found may be related to:

Traceback (most recent call last):
  File "/home/crk_w19039039/VIBRANT/databases/VIBRANT/scripts/VIBRANT_annotation.py", line 1422, in <module>
    model = pickle.load(read_model)
  File "/home/crk_w19039039/.conda/envs/VIBRANT/lib/python3.5/site-packages/numpy/random/_pickle.py", line 2, in <module>
    from .philox import Philox
  File "philox.pyx", line 1, in init numpy.random.philox
  File "__init__.pxd", line 918, in init numpy.random.bit_generator
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject 

Not really sure how to solve this. any help would be greatly appreciated, 

Kind Regards Jlee795

**Comment by BioZhang0831** [comment]
> 确定可能出了什么问题，但看起来数据库没有完全完成设置。您能否尝试删除，

hello i want to know how you solve this problem

**Comment by BioZhang0831** [comment]
> 您好。此问题已解决，Vibrant 现在可以运行。然而，又遇到了另一个问题。我正在运行您的混合示例测试数据集，并查看了 github 页面上的日志文件，您的日志文件显示找到了四个噬菌体，但是当我运行混合测试示例数据集时，我的日志文件显示未找到噬菌体。非常确定我应该在日志中获得与您相同的输出。您对原因有什么建议吗？非常感谢任何帮助。谢谢
> 
> 亲切问候
> 
> 杰利795

hello i want to know how you solve this problem to make vibrant run

**Comment by RKTgbrc** [comment]
I have faced he same issue 
VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.

first i checked the log 
cat VIBRANT/databases/VIBRANT_setup.log

Done with databases. Several new databases are now in this folder.

Verying correct dependency versions ...

VIBRANT v1.2.1 is good to go!
See example_data/ for quick test files.


I saw it was installed well. so I tried running the command with -d flag pointing to database directory and it worked

VIBRANT_run.py -i final-viral-combined.fa -virome -folder vibrant_output -t 30 -d ~/VIBRANT/databases/

**Comment by nikolasbasler** [comment]
This is what worked for me (not sure if all these steps are necessary)

- `download-db.sh /destination/path`
- `python /destination/path/databases/VIBRANT_setup.py`
- Delete both `KEGG_profiles_prokaryotes.HMM.h3i` and `VOGDB94_phage.HMM.h3i` inside `/destination/path/databases/`
- Run `hmmpress` on both `KEGG_profiles_prokaryotes.HMM` and `VOGDB94_phage.HMM`
- In both cases `hmmpress` produced more files than were originally present. 
- Vibrant now runs on my data (I am using `-d` and `-m`)

**Comment by mattewchen** [comment]
> This is what worked for me (not sure if all these steps are necessary)
> 
> * `download-db.sh /destination/path`
> * `python /destination/path/databases/VIBRANT_setup.py`
> * Delete both `KEGG_profiles_prokaryotes.HMM.h3i` and `VOGDB94_phage.HMM.h3i` inside `/destination/path/databases/`
> * Run `hmmpress` on both `KEGG_profiles_prokaryotes.HMM` and `VOGDB94_phage.HMM`
> * In both cases `hmmpress` produced more files than were originally present.
> * Vibrant now runs on my data (I am using `-d` and `-m`)

@nikolasbasler 
Hi, I encountered a same issue:
VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.

However, all the KEGG database files (.h3f, .h3i, .h3p, .h3m) are present in my directory.
I also tried regenerating these files using the hmmpress command, but the same error still occurs.

Could you please help me understand what might be causing this issue and how to resolve it?
Thank you very much!

**Comment by nikolasbasler** [comment]
@mattewchen  
Did you try deleting and re-building files for the VOGDB, too? Until I did that, I also still got this error (maybe even referring to the KEGG databse instead of the VOG database, but I don't remember exactly). 
That would be my only idea at this point.

**Comment by mattewchen** [comment]
@nikolasbasler 
Thank you for your suggestion.
I have tried deleting and re-building both the VOGDB and the KEGG databases, but the same error still occurs.
At this point, I’m not sure what else might be causing the issue.

**Comment by KrisKieft** [comment]
If you installed via conda try installing via github

**Comment by mattewchen** [comment]
@KrisKieft 
Thank you for your help!
After carefully checking the VIBRANT_run.py file yesterday, I realized that the issue was caused by incorrect settings in my -d and -m parameters.
After adjusting them, the problem was resolved.
